name: upload_to_gcp
on:
  push:
    branches: main
jobs:
  upload-to-gcp:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup - gcloud / gsutil
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCS_SA_KEY }}
        project_id: ${{ secrets.GCS_PROJECT }}
        export_default_credentials: true

    - name: Upload to GCS
      run: |-
        gsutil -m rsync -R ./registration gs://${{ secrets.GCS_BUCKET }}/registration/
        gsutil -m rsync -R ./vaccination gs://${{ secrets.GCS_BUCKET }}/vaccination/
        
    - name: Upload to BQ
      run: |-
        find registration -maxdepth 1 -type f -iname "*.csv" -print0 | while IFS= read -r -d '' f; do
          tmp=${f//\//\.} 
          tmp2=${tmp/.csv/}
          bq load --source_format=CSV --allow_quoted_newlines --autodetect --replace=true $tmp2 gs://${{ secrets.GCS_BUCKET }}/$f | true
        done
        find vaccination -maxdepth 1 -type f -iname "*.csv" -print0 | while IFS= read -r -d '' f; do
          tmp=${f//\//\.} 
          tmp2=${tmp/.csv/}
          bq load --source_format=CSV --allow_quoted_newlines --autodetect --replace=true $tmp2 gs://${{ secrets.GCS_BUCKET }}/$f | true
        done
